version: '3.1'

services:

  db:
    image: postgres
    restart: 'no'
    environment:
      POSTGRES_USER: 'iris'
      POSTGRES_PASSWORD: 'jundiahy'
    volumes:
      - 'db:/var/lib/postgresql/data'
  adminer:
    image: adminer
    restart: 'no'
    ports:
      - 8080:8080

volumes:
  db: